version: '3'
services:
  react-app:
    build:
      context: . # to set files directory of our app
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules # disclude folder from map
      - .:/app # map folder inside a container (/app) with folder outside of the container (.). It watches for changes
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"] # overwrite Dockerfile's start comand